### ISSUE TITLE
Invalid <Link> with <a> Child Usage Throughout the Project - Next.js Compatibility Issue

### ISSUE THREAD

**Issue by Demon-Sheriff** [AOSSIE-Org/website#115]
### Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.

**While Running the localhost server, this pops up :**
![Screenshot from 2024-08-04 14-36-14](https://github.com/user-attachments/assets/11726ec0-0096-482e-926d-edeeaeae05f3)

---
**Proposed Solutions:**
1. **Remove `<a>` Tags**: Update the code to remove the nested `<a>` tags and let the `<Link>` component handle the anchor behavior.
    ```jsx
    <Link href="/about">About Us</Link>
    ```
2. **Use `legacyBehavior` Prop**: Retain the `<a>` tags by adding the `legacyBehavior` prop to the `<Link>` component.
    ```jsx
    <Link href="/about" legacyBehavior>
      <a>About Us</a>
    </Link>
    ```

**Affected Files:**
- `components/Navbar.js`
- `pages/index.js`
- `components/Footer.js`

**Additional Context:**
This issue was identified in Next.js version 14.1.3. More details can be found in the Next.js documentation: [Next.js Link Documentation](https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor)

**Comment by Deepakchowdavarapu** [comment]
I would like to work on this Issue.

**Comment by harshit4311** [comment]
I'm aldready working on this issue:)

**Comment by harshit4311** [comment]
Ive raised a pull request, could you please check?

**Comment by Princekumar7999** [comment]
i would really be happy to work on this issue,pls assign it to me,i am working on it !!!

**Comment by Demon-Sheriff** [comment]
> I'm aldready working on this issue:)

sorry, but I have already raised PR for this.

**Comment by Princekumar7999** [comment]
may i also raise PR for it as it is showing that some checks has not been passed.

**Comment by Princekumar7999** [comment]
okay
