### ISSUE TITLE
Copyright update to 2024

### ISSUE THREAD

**Issue by Sushant9473** [AOSSIE-Org/website#117]
![Screenshot 2024-08-04 at 3 41 20 PM](https://github.com/user-attachments/assets/5c7aaa6b-0c33-4f5b-8630-54ab25f9ef27)

update this to 2024

**Comment by Sushant9473** [comment]
please assign this issue to me

**Comment by harshit4311** [comment]
I'm aldready working on this issue:)

**Comment by Sushant9473** [comment]
> I'm aldready started working on this issue:)

i have already raised the PR
