### ISSUE TITLE
Update project ideas list item widget

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/website#2]
### Currently the idea list looks like this:

<img width="899" alt="image" src="https://github.com/AOSSIE-Org/website/assets/41890434/925bef3f-2435-43a7-9631-ec1002e2280b">

### Now we need the following fields:
a) a project title/description 
b) more detailed description of the project (2-5 sentences) 
c) expected outcomes 
d) skills required/preferred 
e) possible mentors 
f) expected size of project (90, 175 or 350 hour).
And if possible, an easy, intermediate or hard/difficult rating of each project.

**Comment by notpritam** [comment]
bhaiya i am working on this , i am creating a updated design with demo fields, please provide me the details if you don't want me to use demo one...

**Comment by SimardeepSingh1450** [comment]
Hey @notpritam , @chandansgowda , I can help out on the coding part since I have worked on NextJS beforehand.

**Comment by SimardeepSingh1450** [comment]
Hey @chandansgowda , I have made a figma design file , see if u like it, i am also attaching a preview :

<img src="https://github.com/AOSSIE-Org/website/assets/92221517/5f52bc44-39e3-4333-9df0-d76038ec9867" width="300"/>
