### ISSUE TITLE
Feature Request: Button to Open Link in New Page

### ISSUE THREAD

**Issue by Harsh10022004** [AOSSIE-Org/website#225]
Description:

I would like to propose a feature enhancement . Currently, the button in the apply page
![Screenshot 2024-08-15 141412](https://github.com/user-attachments/assets/315e0b7b-4ca8-4f80-a8cd-efccca2323d2)
 opens the link in the same page. It would be beneficial to have an option to open this link in a new page/tab for better user experience.

Expected Behavior:

When the user clicks the button, it should open the specified link in a new page/tab.

**Comment by yashathwani** [comment]
i would like to work on this
