### ISSUE TITLE
Update Twitter branding to X

### ISSUE THREAD

**Issue by Harshinireddy05** [AOSSIE-Org/website#250]
### Description:
The website's footer currently displays outdated Twitter branding in logo, as shown in the attached image. Due to Twitter's re-branding to "X", we need to update the logo in the footer.

### Expected Behavior:
The Twitter bird logo should be replaced with the new X logo.

### Actual Behavior:
The old Twitter bird logo is still present in the footer section.

### Screenshot:
![image](https://github.com/user-attachments/assets/7fd2150d-c84e-43d7-99c3-4d9b0c2a0139)

**Comment by Harshinireddy05** [comment]
I'm solving this issue and raising a PR in a while.

**Comment by Vegadjay** [comment]
@Harshinireddy05  It's already changed in #207 but pr is not merged..
