### ISSUE TITLE
 In the project section, the cursor will remain a pointer when hovering over the card.

### ISSUE THREAD

**Issue by Patelaman07** [AOSSIE-Org/website#280]
https://github.com/user-attachments/assets/60d53cb1-6ea7-4624-bfe2-857e0166f61c

On the main page of AOSSIE, in the project section, when we hover over the cards for EduAid, Social Street Smart, Djed and so on, the cursor will remain as a pointer, but it behaves like a text cursor.

**Comment by yashsaraswat2004** [comment]
assigned this issue to me

**Comment by yashithalrao** [comment]
can you please assign this issue to me?

**Comment by Arjun20X** [comment]
please assign this issue to me

**Comment by Arjun20X** [comment]
what exactly is needed here? Do you want to projects section which is one the landing page which show 3 project cards to me modified at it should be a text cursor or you want that it should remain a cursor pointer but it should not be able to select text?

**Comment by varshithreddy7** [comment]
Hello @Patelaman07 I made the PR for the issue did it is useful?

**Comment by arbazahmed07** [comment]
hello @Patelaman07 pls assign me this

**Comment by ayyushx** [comment]
@Patelaman07 Resolved this issue and made a PR to the same.
