### ISSUE TITLE
Update Footer to Include the Year 2024

### ISSUE THREAD

**Issue by ssparser** [AOSSIE-Org/website#314]
The footer of the AOSSIE website currently states:
© 2016-2023 AOSSIE. All rights reserved.

Since it is now the year 2024, the footer needs to be updated to include the current year. This will ensure the website reflects accurate and up-to-date information.

Steps to Reproduce:
	1.	Visit the AOSSIE website.
	2.	Scroll to the footer section.
	3.	Observe that the copyright statement ends with 2023.

Expected Behavior:
<img width="449" alt="Screenshot 2024-12-07 at 5 20 19 PM" src="https://github.com/user-attachments/assets/137bb699-e812-4c06-b99f-79e4b8ef093d">

The footer should state:
© 2016-2024 AOSSIE. All rights reserved.

**Comment by Ajai-Sharan** [comment]
I would like work on this issue. please assign this to me.
